networks:
  automation:
    name: 'automation'
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  app:
    image: mcr.microsoft.com/devcontainers/ruby:1-3.3-bullseye
    networks:
      - automation
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - selenium-hub

  firefox:
    image: selenium/node-firefox:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - automation
    deploy:
      mode: replicated
      replicas: 6

  selenium-hub:
    networks:
      automation:
        ipv4_address: 172.18.0.2
    image: selenium/hub:4.27.0-20250101
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
